### PR TITLE
Throttle

### PR DESCRIPTION
**Pull request by redhog**
Might in the future close https://github.com/ucbepic/docetl/issues/46

Config example

```
config:
  rate_limits:
    embedding_call:
      - count: 1000
        per: 1
        unit: second
    llm_call:
      - count: 1
        per: 1
        unit: second
      - count: 10
        per: 5
        unit: hour
    llm_tokens: # Not implemented yet, don't know how to count tokens easily
      - count: 256
        per: 10
        unit: minute
```

You can easily add more limit types than call, like tokens etc as long as you have a way to calculate nr tokens needed for an llm call (right now only "llm_call" and "embedding_call" are applied).

### CODE REVIEW

**Comment by shreyashankar** [comment]
I added https://github.com/ucbepic/docetl/pull/66 as a quick fix for someone who was having trouble with rate limits in the discord server

**Comment by redhog** [comment]
That's not a bad idea to have /in addition/ to rate limits actually :)

**Comment by redhog** [comment]
@shreyashankar I think this is now ready for merging, if you think it looks ok. It's a fair bit of a refactor:

* DSLRunner and Optimizer now both inherit from Pipeline, which holds the config and console.
* Pipeline holds the rate_limiter object
* Pipeline also holds an instance of  operations.utils.APIWrapper
  * Has all the wrapper methods for litellm.completion
  * Applies all rate limits

The reason the rate_limiter object is not a property of APIWrapper, is that you might potentially want to apply rate limits to things that are not llm calls.

**Comment by shreyashankar** [comment]
Things I added/modified:
- Changed tests to make them pass
- Operation objects don't point to a runner anymore; they point to the APIWrapper object directly
- Parsing tools do not take in `runner` as a parameter; we can revisit this for the parsing functions that require rate limits/when we revamp the parsing tool API anyways
- `Pipeline` API class and `Pipeline` top-level class introduced in this PR both share the same name. This might be confusing. As such, I renamed the `Pipeline` top-level class (not the API class) to `ConfigWrapper`
- Removed the necessary top-level `config` key, so part of the entire yaml config might look like this

```
rate_limits:
    embedding_call:
      - count: 1000
        per: 1
        unit: second
    llm_call:
      - count: 1
        per: 1
        unit: second
      - count: 10
        per: 5
        unit: hour
    llm_tokens: # Not implemented yet, don't know how to count tokens easily
      - count: 256
        per: 10
        unit: minute
 ```

**Comment by redhog** [comment]
I think sending around the runner is useful, as there might be future global things similar to APIWrapper that we might want access too, and this would mean we still only need to send around one thing, instead of refactoring every time we add something. Esp. since the operation api is now a public api (users can register their own operations), refactoring it is a bit annoying to users...

The other changes I think are fine, I esp. don't have much opinion about the exact yaml format :)

**Pull request merged**
