### PR TITLE
#91 document  > item renaming

### PR DESCRIPTION
**Pull request by garuna-m6**
documentation changes generalizing document -> items

### CODE REVIEW

**Comment by garuna-m6** [comment]
I believe at several places the word document makes more sense, please do mention the files that should be altered as well

**Comment by shreyashankar** [comment]
Thanks for this! I don't think there needs to be a code change anywhere; I was imagining just a small rename from `document` to `item` when mentioning datasets in the documentation. 

- https://ucbepic.github.io/docetl/concepts/operators/#overview: "datasets contain documents" -> "datasets contain items"
- https://ucbepic.github.io/docetl/concepts/pipelines/#datasets: "They are collections of documents, where each document" -> "They are collections of items, where each item is a dictionary of key-value pairs in a JSON list"

The other documentation changes you made look good.

**Review by shreyashankar — APPROVED** [review]

**Comment by shreyashankar** [comment]
Thank you! https://github.com/ucbepic/docetl/issues/94 might be a good one to tackle (and has high impact); specifically the part where we want to trace the lineage of source documents. Instead of creating and using a sqlite db, maybe if the user specifies a path in their config for logging traces, we could log traces for each source document? We might have to require an id key for each source document if the user wants to log traces.

**Comment by garuna-m6** [comment]
> Thank you! #94 might be a good one to tackle (and has high impact); specifically the part where we want to trace the lineage of source documents. Instead of creating and using a sqlite db, maybe if the user specifies a path in their config for logging traces, we could log traces for each source document? We might have to require an id key for each source document if the user wants to log traces.

will take some sweet time on this one, need to understand code to expectation context

**Pull request merged**
