### PR TITLE
Add support for LiteLLM proxy

### PR DESCRIPTION
**Pull request by michielree**
Find corresponding issue here: https://github.com/ucbepic/docetl/issues/35

- Proposes to simplify accessing model through a (LiteLLM) proxy by adding an optional top level configuration option `proxy_url` to to configuration files
- API key to proxy can be set with environment variable `DOCETL_PROXY_API_KEY`
- If `proxy_url` is not set all completion / embedding calls are still made through the LiteLLM Python SDK.

Test more or less copy pasted from the Ollama one, we could potentially generalize a bit there.

NB my original intention was to use this to have DocETL use vLLM hosted models. That's still not working because of incompatibility with some of the nested parameters of keyword `function` (`strict` and `additionalProperties`) of `client.chat.completions.create`. Regardless, this should be a useful addition in itself

I'll wait for comments on my general setup before solving the merge conflicts.

### CODE REVIEW

**Comment by michielree** [comment]
I'll wait for comments on my general setup before solving the merge conflicts.

**Comment by shreyashankar** [comment]
#64 Is going to create an`APIWrapper` class, which will allow us to pass configs from the pipeline level directly to the `call_llm` functions. So then we can accept the proxy parameters as you've proposed, but store them in the top-level `ConfigWrapper` component (created by #64), which will then be accessible via `call_llm` and `gen_embeddings` (which will be methods of the `APIWrapper` class). So this means you won't have to pass around parameters to the individual operations.

Hopefully we'll get #64 merged tomorrow 🙏🏽 LMK what you think about this, and if you have any questions!

**Comment by michielree** [comment]
Sounds perfect! I'll close this and create a new PR once #64 is merged.

**Comment by shreyashankar** [comment]
ok, we've merged! The DSLRunner and Optimizer both inherit from this [ConfigWrapper](https://github.com/ucbepic/docetl/blob/6fbe67364400559ece53625c56cf6c2dc9c67113/docetl/config_wrapper.py#L33) class, which is passed around all the operations.

All the LLM calls now have access to this runner object [here](https://github.com/ucbepic/docetl/blob/6fbe67364400559ece53625c56cf6c2dc9c67113/docetl/operations/utils.py#L365).

LMK if you have any questions!

**Pull request closed without merging**
