### PR TITLE
New api

### PR DESCRIPTION
**Pull request by redhog**
Kinda/partially solves https://github.com/ucbepic/docetl/issues/107 

This PR superseeds https://github.com/ucbepic/docetl/pull/111

This supports the following python API:

```
config = yaml.safe_load("""
datasets:
  input:
    type: file
    source: local
    path: "input.json"

operations:
- name: test
  type: unnest
  unnest_key: concepts
  expand_fields:
    - concept

pipeline:
  steps:
    - name: test
      input: input
      operations:
        - test
  output:
    type: file
    path: "output.json"
    intermediate_dir: "output"
""")


pipeline = docetl.DSLRunner(config)
input = pipeline.load()
output, cost = pipeline.run(input)
pipeline.save(output)
```

* `config` is your pipeline config parsed into dictionaries and list
* `input` can be just a dictionary of `{datasetname: [item, item, ...]}` where `item` is  dictionary with item data.
* `output` is just  `[item, item, ...]`

Left to implement is possibility to override intermediate dir outside of the `config`.

### CODE REVIEW

**Comment by redhog** [comment]
```
with open("schema.json", "w") as f: json.dump(docetl.runner.DSLRunner.json_schema, f)
```

This now gives a schema for the entire yaml. Tested with https://json-editor.github.io/json-editor/ which generates a passable form for it (haven't tested validating an existing pipeline yet, so might be buggy) :)

**Comment by shreyashankar** [comment]
I'm getting the error:

```
ImportError while loading conftest '/Users/shreyashankar/Documents/hacking/docetl/tests/conftest.py'.
tests/conftest.py:2: in <module>
    from docetl.operations.map import MapOperation
docetl/__init__.py:3: in <module>
    from docetl.runner import DSLRunner
E     File "/Users/shreyashankar/Documents/hacking/motion-v3/docetl/runner.py", line 43
E       OpType = Union[*[op.schema for op in get_operations().values()]]
E                      ^
E   SyntaxError: invalid syntax
```

**Comment by redhog** [comment]
Oh, that must be a python version problem. Are you on 3.10? I'm on 3.11. I'll see how to construct a union type from a list of types in a variable in earlier pythons...

**Comment by redhog** [comment]
Pushed a fix to that that uses `type1 | type2` instead of `Union[type1, type2]`... It's a bit uglier, but should work in older pythons.

**Comment by shreyashankar** [comment]
I think this all works; I will double check tomorrow and merge it by Monday :-)

**Pull request merged**
